version: '3.7'
services:
  mysql:
      build: 
        context: .
        dockerfile: Dockerfile
      container_name: mysql
      restart: always
      ports: 
        - 23306:3306
      deploy:
        mode: replicated
        replicas: 3
        restart_policy:
          condition: on-failure
      environment:
        MYSQL_ROOT_PASSWORD: "simons83"
        MYSQL_DATABASE: "controlvacacional"
        MYSQL_USER: "pedro"
        MYSQL_PASSWORD: "simons83"
      volumes:
        - ./schemas:/var/lib/mysql:rw
      networks:
        mysql_network:
          aliases:
            - mysql_host
volumes: 
  schemas: {}
networks:
  mysql_network:
    name: mysql_net
    driver: bridge
        
     
      
