version: '3.8'
services:
  mysql:
    image: mysql:latest
    networks:
      - webnet
    volumes:
      - mysql_data:/var/lib/mysql
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "simons83"
      MYSQL_DATABASE: "controlvacacional"
      MYSQL_USER: "pedro"
      MYSQL_PASSWORD: "simons83"
    deploy:
      mode: replicated
      replicas: 2
      labels: [MySQLDB]
      restart_policy:
        condition: on-failure
  backend:
    image: backend
    ports:
      - "3001:3000"
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
  apollo:
    image: apollo
    ports:
      - "4001:4000"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
  frontend:
    image: frontend
    ports:
      - "5001:5000"
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: on-failure
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]


volumes:
  mysql_data:                
networks:
  webnet:
      
